_import:
  - !include benchmark/tasks/NSynth/NSynthI_base_config.yaml

dataset:
  pre_extract:
    accelerator: gpu
    audio_dir: data/NSynth/nsynth-data
    output_dir: data/NSynth/jukemir_features/jukemir_feature_default
    keep_folder_structure: true
    overwrite: true

    audio_loader:
      crop_to_length_in_sec: null

    feature_extractor:
      pretrain:
        !include benchmark/models/jukemir/jukemir.yaml
        force_half: true

  dataset: NSynthI
  input_type: feature # [audio, feature]
  input_dir: data/NSynth/jukemir_features/jukemir_feature_default
  metadata_dir: data/NSynth/nsynth-data

model:    
    downstream_structure:
      components:
        - name: feature_selector
          layer: 0 # we only use a single layer (36) as the jukemir paper suggested
        - name: mlp
          hidden_layer_sizes: [512]
          dropout_p: 0.2
          num_outputs: 10
  